"""added targetcolumn

Revision ID: 0d732b94f158
Revises: 2b6898f70efb
Create Date: 2020-04-16 17:27:46.863195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d732b94f158'
down_revision = '2b6898f70efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('target', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'target')
    # ### end Alembic commands ###
