"""edited text model

Revision ID: 2b6898f70efb
Revises: d34ed98ab40f
Create Date: 2020-04-01 23:22:33.011647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6898f70efb'
down_revision = 'd34ed98ab40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('opinion_towards', sa.String(), nullable=True))
    op.add_column('text', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('text', sa.Column('stance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'stance')
    op.drop_column('text', 'sentiment')
    op.drop_column('text', 'opinion_towards')
    # ### end Alembic commands ###
